import type { Metadata } from "next";

import { LegalPage } from "@/components/legal-page";
import { absoluteUrl, SITE_NAME } from "@/lib/site";

const TITLE = "AI Assistant Disclosure — Knotty AI";
const DESCRIPTION =
  "How Knotty AI works on MasseurMatch, what AI responses can and cannot be used for, and your responsibilities when using AI-assisted features.";
const PATH = "/ai-disclosure";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: absoluteUrl(PATH) },
  openGraph: {
    type: "website",
    url: absoluteUrl(PATH),
    siteName: SITE_NAME,
    title: TITLE,
    description: DESCRIPTION,
  },
};

export default function Page() {
  return (
    <LegalPage title={TITLE} path={PATH} lastUpdated="June 29, 2026">
      <>
        <div>
          <section>
            <p>AI Features</p>

            <p>
              MasseurMatch includes Knotty AI, an artificial intelligence assistant designed to help
              users discover providers and navigate the platform. This page explains what Knotty AI
              is, what it can do, what it cannot do, and your responsibilities when using it.
            </p>
          </section>

          <section>
            <div>
              <div>
                <h2>What is Knotty AI?</h2>
                <div>
                  <p>
                    Knotty AI is an AI-powered assistant integrated into the MasseurMatch platform.
                    It uses large language models to answer questions about the directory, help
                    users find relevant providers, explain how the platform works, and offer general
                    wellness discovery guidance.
                  </p>
                  <p>
                    Knotty AI is built to serve as a helpful starting point for discovery — not as a
                    source of authoritative advice or verified information.
                  </p>
                </div>
              </div>
            </div>
          </section>

          <section>
            <h2>Important limitations</h2>
            <div>
              <h3>AI responses may be inaccurate</h3>
              <p>
                AI-generated responses are generated by language models that can produce incorrect,
                outdated, or misleading information. Always independently verify important
                information before acting on it.
              </p>
              <h3>Not professional advice</h3>
              <p>
                Knotty AI does not provide legal, medical, safety, licensing, tax, financial, or
                professional advice of any kind. Nothing Knotty AI says should be treated as a
                substitute for professional consultation.
              </p>
              <h3>Not a safety guarantee</h3>
              <p>
                Knotty AI cannot verify provider credentials, conduct background checks, or assess
                personal safety situations. Do not rely on AI responses to evaluate whether a
                provider is safe, licensed, or appropriate for your needs.
              </p>
              <h3>Not always up to date</h3>
              <p>
                AI models have knowledge cutoffs and may not reflect the most recent licensing laws,
                regulations, pricing, or platform updates. Check official sources for time-sensitive
                information.
              </p>
              <h3>Not emergency services</h3>
              <p>
                If you are in immediate danger or experiencing an emergency, contact local emergency
                services. Knotty AI is not a crisis resource, hotline, or emergency response system.
              </p>
              <h3>Responses may be inappropriate</h3>
              <p>
                Despite guardrails and safety filters, AI systems may occasionally produce responses
                that are unhelpful, off-topic, or inappropriate. Please use your own judgment when
                evaluating AI output.
              </p>
            </div>
          </section>

          <section>
            <div>
              <div>
                <h2>Your responsibility</h2>
                <div>
                  <p>
                    You are responsible for independently verifying any important information before
                    making decisions based on AI responses. This includes verifying provider
                    credentials, licensing, pricing, availability, safety, and suitability.
                  </p>
                  <p>
                    AI-generated suggestions are informational starting points only. They are not
                    endorsements, recommendations, guarantees, or assessments of any individual
                    provider.
                  </p>
                </div>
              </div>
            </div>
          </section>

          <section>
            <div>
              <div>
                <h2>Data and privacy</h2>
                <div>
                  <p>
                    Conversations with Knotty AI may be processed to operate, improve, monitor, and
                    secure the AI service. AI interaction data is handled in accordance with our
                    <a href="/privacy">Privacy Policy</a>.
                  </p>
                  <p>
                    Do not share sensitive personal information — such as passwords, financial
                    account details, or private health information — with Knotty AI. AI
                    conversations are not a secure channel for transmitting confidential data.
                  </p>
                </div>
              </div>
            </div>
          </section>

          <section>
            <p>Related Policies</p>
          </section>
        </div>
      </>
    </LegalPage>
  );
}
