import { Card } from "@masseurmatch/ui";
import type { Metadata } from "next";
import Link from "next/link";

import { requireAdmin } from "@/lib/guards";

export const metadata: Metadata = {
  title: "Admin Tools",
  robots: { index: false, follow: false },
};

const ACTIVE_TOOLS = [
  ["People / Profile CMS", "/people", "Edit real provider profile data; approval, verification and billing stay in their dedicated workflows."],
  ["Email Center", "/emails", "Templates, campaigns, suppressions and the production lifecycle email queue."],
  ["Messaging", "/messaging", "Inbox, opt-outs, Knotty controls and the outbound transport queue."],
  ["Profile Imports", "/migrations", "Review imported testimonials and migration evidence atomically."],
  ["Blog CMS", "/blog", "Edit the exact database posts rendered by the public blog."],
  ["Cities", "/cities", "Live coverage derived from provider profiles instead of the legacy file store."],
  ["Demand Radar", "/demand-radar", "Current operational replacement for legacy keyword-trend screens."],
  ["Analytics", "/analytics", "Current profile/search/ranking analytics."],
  ["Billing", "/billing", "Live PayPal subscription state and health."],
] as const;

const REPLACEMENTS = [
  ["/admin/profile-cms", "People", "Profile data is edited where the provider record actually lives."],
  ["/admin/keywords", "Demand Radar", "The old content-store keyword list is not a V2 source of truth."],
  ["/admin/dashboard/keyword-trends", "Demand Radar", "Consolidated into the live demand workflow."],
  ["/admin/sms", "Messaging", "The legacy Twilio campaign screen is replaced by the current messaging queue/Knotty operations."],
  ["/admin/resend-topics", "Email Center", "Email operations are consolidated around the lifecycle queue and provider preferences."],
  ["/admin/settings", "This hub + code/env configuration", "The legacy site_settings row is not consumed by V2 runtime, so exposing an editor would create a false control."],
  ["/admin/legal", "Public Legal Center", "Legal documents are managed as production website content, not duplicated in an admin shell."],
  ["/admin/onboarding", "Provider sign-up", "Operational onboarding lives in the provider dashboard."],
] as const;

const RETIRED = [
  ["Bookings", "MasseurMatch is a directory, not a client/provider booking marketplace."],
  ["A/B tests placeholder", "The legacy page did not implement a real experiment system."],
  ["Design-system spike", "Developer demonstration content, not an operational product feature."],
  ["Legacy SEO control cards", "The old controls had no write actions. V2 SEO is generated by real routes, metadata, sitemap and structured data."],
] as const;

export default async function ToolsPage() {
  await requireAdmin("/tools");

  return (
    <main className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-6 sm:py-12">
      <header>
        <p className="text-xs font-semibold uppercase tracking-[0.18em] text-wine">Operations</p>
        <h1 className="mt-2 text-3xl font-semibold text-ink">Admin Tools & Parity</h1>
        <p className="mt-2 max-w-3xl text-sm text-ink/60">
          Operational entry points for V2 and the explicit destination of legacy Admin functions.
          This page intentionally avoids controls that do not change production behavior.
        </p>
      </header>

      <section className="mt-8">
        <h2 className="text-lg font-semibold text-ink">Active tools</h2>
        <div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">
          {ACTIVE_TOOLS.map(([label, href, description]) => (
            <Link key={href} href={href} className="block">
              <Card className="h-full p-5 transition hover:border-wine/30 hover:shadow-sm">
                <p className="font-semibold text-ink">{label}</p>
                <p className="mt-2 text-sm leading-relaxed text-ink/55">{description}</p>
                <p className="mt-4 text-xs font-semibold text-wine">Open →</p>
              </Card>
            </Link>
          ))}
        </div>
      </section>

      <section className="mt-10">
        <h2 className="text-lg font-semibold text-ink">Legacy route replacements</h2>
        <Card className="mt-3 overflow-x-auto">
          <table className="w-full min-w-[820px] text-left text-sm">
            <thead className="border-b border-ink/10 text-xs uppercase tracking-wide text-ink/45">
              <tr>
                <th className="px-4 py-3">Legacy route</th>
                <th className="px-4 py-3">V2 destination</th>
                <th className="px-4 py-3">Reason</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-ink/10">
              {REPLACEMENTS.map(([route, destination, reason]) => (
                <tr key={route}>
                  <td className="px-4 py-3 font-mono text-xs text-ink">{route}</td>
                  <td className="px-4 py-3 font-medium text-wine">{destination}</td>
                  <td className="px-4 py-3 text-ink/60">{reason}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Card>
      </section>

      <section className="mt-10">
        <h2 className="text-lg font-semibold text-ink">Intentionally retired</h2>
        <div className="mt-3 grid gap-3 md:grid-cols-2">
          {RETIRED.map(([name, reason]) => (
            <Card key={name} className="p-5">
              <p className="font-semibold text-ink">{name}</p>
              <p className="mt-2 text-sm text-ink/55">{reason}</p>
            </Card>
          ))}
        </div>
      </section>

      <section className="mt-10 rounded-2xl border border-ink/10 bg-ink/[0.025] p-5">
        <h2 className="font-semibold text-ink">External operational surfaces</h2>
        <div className="mt-3 flex flex-wrap gap-3 text-sm font-medium">
          <a href="https://www.masseurmatch.com/legal" target="_blank" rel="noreferrer" className="text-wine hover:underline">Legal Center ↗</a>
          <a href="https://www.masseurmatch.com/sitemap.xml" target="_blank" rel="noreferrer" className="text-wine hover:underline">Sitemap ↗</a>
          <a href="https://dashboard.masseurmatch.com/sign-up" target="_blank" rel="noreferrer" className="text-wine hover:underline">Provider sign-up ↗</a>
          <a href="https://dashboard.masseurmatch.com/api/health/billing" target="_blank" rel="noreferrer" className="text-wine hover:underline">Billing health ↗</a>
        </div>
      </section>
    </main>
  );
}
